data = {
    "symptoms": [
        "fever headache", "cough cold", "sore throat", "stomach pain",
        "body ache", "runny nose", "high fever", "nausea vomiting",
        "chest pain", "shortness of breath", "skin rash", "dizziness",
        "muscle pain", "joint pain", "fatigue", "loss of taste smell",
        "sneezing", "ear pain", "red eyes", "constipation",
        "diarrhea", "bloating", "acid reflux", "migraine",
        "insomnia", "anxiety", "depression", "hypertension",
        "low blood pressure", "high blood sugar", "low blood sugar", "palpitations",
        "swollen lymph nodes", "yellow skin", "dark urine", "lightheadedness",
        "dry cough", "wet cough", "sore muscles", "numbness",
        "tingling", "burning sensation", "itchy skin", "frequent urination",
        "urinary pain", "blood in urine", "abdominal cramps", "back pain",
        "neck pain", "shoulder pain", "leg cramps", "cold sweats",
        "hot flashes", "blurred vision", "eye strain", "ear ringing",
        "memory loss", "difficulty swallowing", "hoarseness", "chest tightness",
        "excessive thirst", "frequent hunger", "weight loss", "weight gain",
        "hair loss", "brittle nails", "dry mouth", "bad breath",
        "excessive sweating", "night sweats", "weakness", "swelling in feet",
        "painful joints", "stiff neck", "frequent infections", "slow healing wounds"
    ],
    "medicine": [
        "Paracetamol", "Benadryl", "Lozenges", "Antacid",
        "Ibuprofen", "Cetirizine", "Dolo 650", "Domperidone",
        "Aspirin", "Salbutamol", "Hydrocortisone", "Meclizine",
        "Naproxen", "Diclofenac", "Energy Booster", "Zinc Supplements",
        "Antihistamine", "Antibiotic Ear Drops", "Lubricant Eye Drops", "Laxative",
        "Oral Rehydration Salts", "Simethicone", "Omeprazole", "Rizatriptan",
        "Melatonin", "Sertraline", "Fluoxetine", "Amlodipine",
        "Losartan", "Metformin", "Glucose Tablets", "Beta Blockers",
        "Antiviral", "Liver Detox Supplement", "Bile Acid Binder", "Iron Supplement",
        "Cough Syrup", "Expectorant", "Muscle Relaxant", "Vitamin B12",
        "Nerve Pain Reliever", "Burn Cream", "Antifungal Cream", "Diuretic",
        "Urinary Tract Analgesic", "Cranberry Supplements", "Antispasmodic", "Muscle Pain Reliever",
        "NSAIDs", "Heat Rub", "Leg Cramp Relief", "Hormone Therapy",
        "Menopause Relief", "Eye Drops", "Blue Light Glasses", "Tinnitus Masker",
        "Memory Booster", "Swallowing Aid", "Vocal Cord Soother", "Bronchodilator",
        "Insulin", "Blood Sugar Stabilizer", "Appetite Stimulant", "Appetite Suppressant",
        "Hair Growth Supplement", "Nail Strengthener", "Mouthwash", "Breath Freshener",
        "Sweat Control Wipes", "Cooling Gel", "Electrolyte Solution", "Foot Swelling Relief",
        "Joint Support Supplement", "Neck Pain Patches", "Immune Booster", "Healing Ointment"
    ]
}
